### ISSUE TITLE
Files opened with telescope in neovim start in insert mode

### ISSUE THREAD

**Issue by laurigates** [laurigates/dotfiles#4]
I'm not sure if this has something to do with my configuration, but it's annoying when this happens.
It should start in normal mode.

**Comment by laurigates** [comment]
Related Telescope issues, apparently fixed:
- https://github.com/nvim-telescope/telescope.nvim/issues/2027
- https://github.com/nvim-telescope/telescope.nvim/issues/2501

**Comment by vE5li** [comment]
Is there any progress on this? I would also be happy to create a PR myself if someone can point me in a direction

**Comment by SirRuBick** [comment]
I have the same problem

**Comment by laurigates** [comment]
Haven't noticed this issue for a while now
